before_script:
  - apt-get update -qq
  - apt-get install -qq git dos2unix
  - mkdir ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - echo $SSH_PRIVATE_KEY >> ~/.ssh/key_64.pem
  - cat ~/.ssh/key_64.pem |base64 -d > ~/.ssh/key.pem
  - chmod 400 ~/.ssh/key.pem
  - eval "$(ssh-agent -s)"
  - cat ~/.ssh/key.pem
  - echo $IP_REMOTE
  - which ssh-agent
  - echo $ENVQA >> ~/.ssh/env
  - cat ~/.ssh/env |base64 -d > ~/.ssh/.env
  
    ##SSH PRO
  - echo $SSH_PRIVATE_KEY_PRO >> ~/.ssh/key_64_PRO.pem
  - cat ~/.ssh/key_64_PRO.pem |base64 -d > ~/.ssh/key_PRO.pem
  - chmod 400 ~/.ssh/key_PRO.pem
  - eval "$(ssh-agent -s)"
  - which ssh-agent


deploy_qa:
  stage: deploy
  script:
    - ssh  -i ~/.ssh/key.pem $USUARIO@$IP_REMOTEQA " cd $DOCUMENT_ROOT/ && sudo git checkout qa && sudo git pull "
    - ssh  -i ~/.ssh/key.pem $USUARIO@$IP_REMOTEQA " cd $DOCUMENT_ROOT/ && sudo docker build -t paso2 . "
  only:
    - qa

deploy_produccion:
  stage: deploy
  script:
    - ssh  -i ~/.ssh/key_PRO.pem $USUARIO@$IP_REMOTEPRO " cd $DOCUMENT_ROOT/ && sudo git checkout main && sudo git pull "
    - ssh  -i ~/.ssh/key_PRO.pem $USUARIO@$IP_REMOTEPRO " cd $DOCUMENT_ROOT/ && sudo docker build -t paso2 . "
  only:
    - main
